# An example configuration file for MPD.

music_directory			"~/Musique"
playlist_directory		"~/.config/mpd/playlists"
db_file			        "~/.config/mpd/mpd.db"
log_file			"~/.config/mpd/mpd.log"
pid_file			"~/.config/mpd/mpd.pid"
state_file			"~/.config/mpd/mpdstate"

audio_output {
	type			"pulse"
	name			"pulse audio"
}

#The FIFO output is needed for a visualiser plugin which is used by the media-sound/ncmpcpp client. Following additional settings enable the FIFO functionality:
audio_output {
        type  			"fifo"
        name  			"mpdFIFO"
        path  			"/tmp/mpd.fifo"
        enabled  		"yes"
        format  		"44100:16:2"
}

#input {
#        plugin 			"curl"
#}

bind_to_address			"127.0.0.1"
port				"6600"
