[Connection]
host = 0.0.0.0
port = 6600
# password = votre_mot_de_passe_si_necessaire

[Library]
music_dir = ~/Musique
cover_regex = ^(album|cover|\.?folder).*\.(gif|jpeg|jpg|png)$

[Bling]
notify = True
notify_paused = True
mmkeys = True
cdprev = True

[Notify]
urgency = 1
timeout = -1
